# Generated by Django 3.2.5 on 2021-09-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('UserName', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('Re_Password', models.CharField(max_length=250)),
            ],
        ),
    ]
