# Generated by Django 3.2.5 on 2021-09-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_gk_knowledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gk_knowledge',
            old_name='Option_d',
            new_name='answer',
        ),
    ]
