# Generated by Django 3.2.5 on 2021-09-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_option_d_gk_knowledge_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='client1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(max_length=250)),
                ('Last', models.CharField(max_length=250)),
                ('Phone', models.IntegerField()),
                ('Query', models.CharField(max_length=250)),
            ],
        ),
    ]
