# Generated by Django 3.2.5 on 2021-09-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_client1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
